SELECT CAB.CODEMP, CAB.NUNOTA,
    CASE CAB.CODTIPOPER
        WHEN 1000 THEN 'PED. RESERVA' WHEN 1001 THEN 'VENDA FUTURA' WHEN 1002 THEN 'PED. SEM EST' WHEN 1003 THEN 'BONIFICAÇÃO'
        WHEN 1005 THEN 'RJ PED. RESERVA' WHEN 1006 THEN 'RJ VENDA FUTURA' WHEN 1007 THEN 'RJ PED. SEM EST' WHEN 1008 THEN 'RJ BONIFICAÇÃO'
        ELSE 'OUTROS' END AS CODTIPOPER,

    PAR.RAZAOSOCIAL, PRO.DESCRPROD,
    (SELECT SUM(NVL(TGFPRO.PESOBRUTO,0) * TGFITE.QTDNEG) FROM TGFITE
        INNER JOIN TGFPRO ON TGFITE.CODPROD = TGFPRO.CODPROD
        WHERE TGFITE.NUNOTA = CAB.NUNOTA AND TGFITE.USOPROD = 'D') PESO,
     CAB.DTNEG, CAB.DTPREVENT DT_TRANSF,
    (SELECT (CASE WHEN CAB.CODTIPOPER = 900 AND CAB.STATUSNOTA = 'L' AND CAB.PENDENTE = 'S' THEN 'ORC PLANEJADO' ELSE
            (CASE WHEN MAX(LIB.ORDEM) IS NULL AND CAB.STATUSNOTA = 'A' AND CAB.PENDENTE = 'S' THEN 'PLANEJADO'  ELSE
            (CASE WHEN MAX(LIB.ORDEM) = '1' AND MAX(LIB.VLRLIBERADO) = 0 THEN 'CRÉDITO' ELSE
            (CASE WHEN MAX(LIB.REPROVADO) = 'S' AND MAX(LIB.VLRLIBERADO) = 0 THEN 'REPROVADO' ELSE
            (CASE WHEN MAX(LIB.ORDEM) = '2' AND MAX(LIB.VLRLIBERADO) = 0 THEN 'LIBERAR OP' ELSE
            (CASE WHEN MAX(LIB.ORDEM) = '2' AND MAX(LIB.VLRLIBERADO) > 0 AND CAB.PENDENTE = 'S' THEN 'LIBERADO'  ELSE
            (CASE WHEN MAX(LIB.ORDEM) = '2' AND MAX(LIB.VLRLIBERADO) > 0 AND CAB.PENDENTE = 'N' THEN 'TRANSPORTE' ELSE
            --(CASE WHEN MAX(LIB.ORDEM) = '2' AND MAX(LIB.VLRLIBERADO) = MAX(LIB.VLRATUAL) AND CAB.STATUSNOTA = 'A' AND CAB.PENDENTE = 'N' THEN 'PRODUZIDO' ELSE
            (CASE WHEN CAB.CODTIPOPER IN (1003,1008) AND MAX(LIB.VLRLIBERADO) = 0 AND CAB.PENDENTE = 'S' THEN 'LIBERAR OP' ELSE
            (CASE WHEN CAB.CODTIPOPER IN (1003,1008) AND MAX(LIB.VLRLIBERADO) > 0 AND CAB.PENDENTE = 'S' THEN 'LIBERADO' ELSE
            (CASE WHEN CAB.CODTIPOPER IN (1003,1008) AND MAX(LIB.VLRLIBERADO) > 0 AND CAB.PENDENTE = 'N' THEN 'TRANSPORTE' ELSE
            --(CASE WHEN CAB.CODTIPOPER = 1117 AND CAB.STATUSNOTA = 'L' AND CAB.PENDENTE = 'S' THEN 'RESERVADO' ELSE
            'PROVISORIO' END) END) END) END) END) END) END) END) END) END) END) END) AS LABEL
            --FROM TSILIB LIB INNER JOIN TGFCAB C ON CAB.NUNOTA = LIB.NUCHAVE WHERE C.CODEMP = CAB.CODEMP) FIN_PCP,
    --ITE.QTDNEG, OPTION_LABEL('TGFCAB','MODENTREGA',CAB.MODENTREGA) MODENTREGA, CAB.AD_VALOR_FRETE,
    --(SELECT CID.NOMECID FROM TGFCAB CCID
        --LEFT JOIN TGFCTT CTT ON CTT.CODPARC = CCID.CODPARC AND CTT.CODCONTATO = CCID.CODCONTATO
        --INNER JOIN TGFPAR PCID ON PCID.CODPARC = CCID.CODPARC
        --INNER JOIN TSICID CID ON CID.CODCID = CASE WHEN CTT.CODCID IS NULL OR  CTT.CODBAI IS NULL OR CTT.CODEND IS NULL THEN  PCID.CODCID ELSE CTT.CODCID END
    --WHERE CCID.NUNOTA = CAB.NUNOTA AND CCID.CODEMP = CAB.CODEMP) AS NOMECID,
    --UFS.UF UFDESTINO,  ITE.VLRTOT/ITE.QTDNEG PRECO, CAB.AD_MARGEMMEDIA, VEN.APELIDO, USU.NOMEUSU,


    --NVL(TO_CHAR(DTPREVENT-1),'') DTFAB,  CAB.DTPREVENT

    FROM TGFCAB CAB
    INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
    INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA AND ITE.USOPROD ='V'
    INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
    INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
    INNER JOIN TGFITE ITEPA ON ITEPA.NUNOTA = CAB.NUNOTA AND ITEPA.USOPROD='V'
    INNER JOIN TGFLOC LOC ON ITEPA.CODLOCALORIG = LOC.CODLOCAL
    INNER JOIN TGFTPV TPV ON TPV.CODTIPVENDA = CAB.CODTIPVENDA AND CAB.DHTIPVENDA = TPV.DHALTER
    INNER JOIN TSICID CID ON CID.CODCID = PAR.CODCID
    INNER JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
    INNER JOIN TSIUSU USU ON USU.CODUSU = STP_GET_CODUSULOGADO


        ORDER BY CAB.CODEMP, DTPREVENT, CAB.NUNOTA ASC