SELECT CAM.NOMETAB
       , TAB.DESCRTAB
       , CAM.NOMECAMPO
       , CAM.DESCRCAMPO
       , CASE WHEN CAM.CALCULADO = 'N' THEN 'Não' ELSE 'Sim' END AS CALCULADO
       , COUNT(1) AS QTD
    FROM TDDCAM CAM
    INNER JOIN TDDTAB TAB ON CAM.NOMETAB = TAB.NOMETAB
     AND SUBSTR(CAM.NOMECAMPO,1,3)='AD_'
     --AND (CAM.NOMETAB = :A_NOMETAB OR :A_NOMETAB IS NULL)
     AND CAM.CALCULADO = 'S'
GROUP BY CAM.NOMETAB
       , TAB.DESCRTAB
       , CAM.NOMECAMPO
       , CAM.DESCRCAMPO
       , CAM.CALCULADO
ORDER BY CAM.NOMETAB
       , CAM.DESCRCAMPO