#type.sql#
SELECT 
CODFAIXA
FROM (SELECT 
    CASE
        WHEN CTT.CEP=0 OR CTT.CEP IS NULL THEN PAR.CEP
        ELSE CTT.CEP
    END AS CEP,
    CID.UF
FROM 
    TGFCAB CAB 
        INNER JOIN TSIEMP EMP ON EMP.CODEMP=CAB.CODEMP
        INNER JOIN TSICID CID ON CID.CODCID=EMP.CODCID
        INNER JOIN TGFPAR PAR ON PAR.CODPARC=CAB.CODPARC 
        LEFT JOIN TGFCTT CTT ON CAB.CODPARC=CTT.CODPARC AND CAB.CODCONTATO=CTT.CODCONTATO
WHERE 
    CAB.NUNOTA=TGFCAB.NUNOTA)
 A INNER JOIN AD_TBHFAIXACEP FAIXA ON FAIXA.CODUF=A.UF AND A.CEP BETWEEN FAIXA.CEPINI AND FAIXA.CEPFIN