SELECT PRO.DESCRPROD, CAB.CODTIPOPER, SUM(CAB.VLRNOTA) VLRTT,
OPTION_LABEL('TGFCAB','MODENTREGA',CAB.MODENTREGA) MODALIDADE,
CASE WHEN MAX(LIB.ORDEM) IS NULL THEN SUM(CAB.QTDVOL) ELSE 0 END AS QTDDPEND,
CASE WHEN MAX(LIB.ORDEM) = 1 THEN SUM(CAB.QTDVOL) ELSE 0 END AS QTDCREDITO,
CASE WHEN MAX(LIB.ORDEM) = 2 THEN SUM(CAB.QTDVOL) ELSE 0 END AS QTDLIBERADO

FROM TSILIB LIB
INNER JOIN TSIUSU USU ON LIB.CODUSULIB = USU.CODUSU
INNER JOIN TGFCAB CAB ON CAB.NUNOTA = LIB.NUCHAVE
LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFEST EST ON EST.CODPROD = ITE.CODPROD
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD

WHERE CAB.DTNEG > '01/07/2023'
AND CAB.TIPMOV IN ('P', 'V')
AND ITE.CODLOCALORIG = 1040000
AND PRO.AD_CESTA = 'S'
AND CAB.CODTIPOPER IN (1012,1013,1014,1015) --1020 SEM RESERVA

GROUP BY CAB.CODTIPOPER, CAB.MODENTREGA, PRO.DESCRPROD