CabecalhoNota.NUNOTA IN (SELECT C.NUNOTA
FROM 
    TGFCAB C
WHERE C.ORDEMCARGA IS NULL
AND NUNOTA NOT IN (
SELECT 
    CAB.NUNOTA
FROM 
    TGFCAB CAB
        INNER JOIN TGFVAR VAR ON VAR.NUNOTA=CAB.NUNOTA
        INNER JOIN TGFCAB CAB2 ON CAB2.NUNOTA=VAR.NUNOTAORIG
WHERE 
    CAB.CODTIPOPER IN (1004,1124) 
    AND CAB.NUNOTA!=VAR.NUNOTAORIG 
    AND  CAB2.STATUSNOTA!='L'
GROUP BY 
    CAB.NUNOTA))