SELECT CAM.NOMETAB, CAM.NOMECAMPO, PCO.VALOR , PCO.OPCAO
FROM TDDCAM CAM
INNER JOIN TDDOPC PCO ON PCO.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB = 'TGFCAB'
AND CAM.NOMECAMPO = 'STATUSNFE'
ORDER BY PCO.OPCAO ASC, OPCAO ASC