with a as (
SELECT
    CAB.NUMNOTA,
    CAB.NUNOTA,
	CAB.DTNEG,
    NVL(PRO.REFERENCIA,ITE.CODPROD) REFERENCIA,
    ITE.CODPROD,
	PRO.DESCRPROD,
	ITE.CONTROLE,
    ITE.USOPROD,
    NVL(PROV.CODPROD,PRO.CODPROD) CODCESTA,
    NVL(PROV.DESCRPROD,PRO.DESCRPROD) CESTA,
    --SUM(ROUND(ITE.QTDNEG/NVL(ITEPA.QTDNEG,ITE.QTDNEG), 4)) UNIT,
    SUM(ITE.QTDNEG) QTDNEG,
    SUM(NVL(ITEPA.QTDNEG,ITE.QTDNEG)) QTDNEGPA,
    PAR.CODPARC,
    PAR.RAZAOSOCIAL,
    PRO.PESOLIQ PESO,
    ITE.CODLOCALORIG,
    LOC.DESCRLOCAL,
    VEN.APELIDO,
    ITE.CODVOL,
    NVL(TO_CHAR(DTPREVENT-1),'') DTFAB,
     CASE CAB.MODENTREGA  WHEN 'N' THEN 'Entrega Direta'
                          WHEN 'P' THEN 'Porta-a-Porta'
                          WHEN 'S' THEN 'Sem Entrega'
                          WHEN 'F' THEN 'Multientrega Faturar para'
                          WHEN 'A' THEN 'Auto Distribuição'
                          WHEN 'M' THEN 'Multientrega'

     ELSE '' END AS MODENTREGA,
     NVL(ITEPA.VLRUNIT,ITE.VLRUNIT) VLRUNIT,
     CAB.AD_MARGEMMEDIA,
     CAB.AD_VALOR_FRETE,
     TPV.DESCRTIPVENDA,
     (SELECT DTVAL FROM TGFEST WHERE TGFEST.CODEMP = CAB.CODEMP AND TGFEST.CODPROD = ITE.CODPROD AND ITE.CONTROLE = TGFEST.CONTROLE AND ITE.CODLOCALORIG=TGFEST.CODLOCAL GROUP BY DTVAL) as DTVAL,
     NVL(ITEPA.CODPROD,ITE.CODPROD) CODPRODPA,
     --((NVL(ITEPA.QTDNEG,ITE.QTDNEG)/ITE.QTDNEG) * PRO.PESOLIQ) PESO_UNIT
    SUM((ITE.QTDNEG*PRO.PESOLIQ)/ITEPA.QTDNEG) PESO_UNIT
FROM TGFCAB CAB
INNER JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA AND LIB.EVENTO IN (3) AND ((LIB.DHLIB IS NOT NULL AND LIB.VLRLIBERADO >= LIB.VLRATUAL) OR LIB.DHLIB IS NULL)
INNER JOIN TGFLIC LIC ON LIC.CODTIPOPER=CAB.CODTIPOPER AND LIC.EVENTO=3 AND LIC.SEQUENCIA=2 AND LIC.CODUSULIB = LIB.CODUSULIB
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA AND ITE.USOPROD IN ('R','D')
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
INNER JOIN TGFTOP TP ON TP.CODTIPOPER = CAB.CODTIPOPER AND TP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = TP.CODTIPOPER)
LEFT JOIN TGFITE ITEPA ON ITEPA.NUNOTA = CAB.NUNOTA AND ITEPA.USOPROD='V'
--INNER JOIN TGFITE ITEO ON ITEO.NUNOTA = VAR.NUNOTAORIG AND ITEO.SEQUENCIA = VAR.SEQUENCIAORIG AND ITEO.USOPROD = 'V'
LEFT JOIN TGFLOC LOC ON LOC.CODLOCAL = NVL(ITEPA.CODLOCALORIG,ITE.CODLOCALORIG)
LEFT JOIN TGFPRO PROV ON PROV.CODPROD = ITEPA.CODPROD
INNER JOIN TGFTPV TPV ON TPV.CODTIPVENDA = CAB.CODTIPVENDA AND CAB.DHTIPVENDA = TPV.DHALTER
WHERE CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN AND
(:DF is null or  CAB.DTNEG <= :DF) AND
(:NROUNICO is null or   CAB.NUNOTA in (:NROUNICO) )
AND (CAB.STATUSNFE <> 'A' OR CAB.STATUSNFE IS NULL)
AND CAB.CODEMP = :CODEMP
AND NVL(TP.AD_ORDEMFAB,'N') = 'S'


GROUP BY
    CAB.NUMNOTA,
    CAB.NUNOTA,
	CAB.DTNEG,
    PRO.REFERENCIA,
    ITE.CODPROD,
	PRO.DESCRPROD,
	ITE.CONTROLE,
    ITE.USOPROD,
    PROV.CODPROD,
    PRO.CODPROD,
    PROV.DESCRPROD,
    PRO.DESCRPROD,
    PAR.CODPARC,
    PAR.RAZAOSOCIAL,
    PRO.PESOLIQ,
    ITE.CODLOCALORIG,
    LOC.DESCRLOCAL,
    VEN.APELIDO,
    ITE.CODVOL,
    ITEPA.VLRUNIT,
    ITEPA.CODPROD,
    ITE.VLRUNIT,
     CAB.AD_MARGEMMEDIA,
     CAB.AD_VALOR_FRETE,
     TPV.DESCRTIPVENDA,
     CAB.MODENTREGA,
     ITE.CONTROLE,CAB.CODEMP
,DTPREVENT


UNION ALL

SELECT
    CAB.NUMNOTA,
    CAB.NUNOTA,
	CAB.DTNEG,
    NVL(PRO.REFERENCIA,ITE.CODPROD) REFERENCIA,
    ITE.CODPROD,
	PRO.DESCRPROD,
	ITE.CONTROLE,
    ITE.USOPROD,
    NVL(PROV.CODPROD,PRO.CODPROD) CODCESTA,
    NVL(PROV.DESCRPROD,PRO.DESCRPROD) CESTA,
    --SUM(ROUND(ITE.QTDNEG/NVL(ITEPA.QTDNEG,ITE.QTDNEG), 4)) UNIT,
    SUM(ITE.QTDNEG) QTDNEG,
    SUM(NVL(ITEPA.QTDNEG,ITE.QTDNEG)) QTDNEGPA,
    PAR.CODPARC,
    PAR.RAZAOSOCIAL,
    PRO.PESOLIQ PESO,
    ITE.CODLOCALORIG,
    LOC.DESCRLOCAL,
    VEN.APELIDO,
    ITE.CODVOL,
    NVL(TO_CHAR(DTPREVENT-1),'') DTFAB,
     CASE CAB.MODENTREGA  WHEN 'N' THEN 'Entrega Direta'
                          WHEN 'P' THEN 'Porta-a-Porta'
                          WHEN 'S' THEN 'Sem Entrega'
                          WHEN 'F' THEN 'Multientrega Faturar para'
                          WHEN 'A' THEN 'Auto Distribuição'
                          WHEN 'M' THEN 'Multientrega'

     ELSE '' END AS MODENTREGA,
     NVL(ITEPA.VLRUNIT,ITE.VLRUNIT) VLRUNIT,
     CAB.AD_MARGEMMEDIA,
     CAB.AD_VALOR_FRETE,
     TPV.DESCRTIPVENDA,
     (SELECT DTVAL FROM TGFEST WHERE TGFEST.CODEMP = CAB.CODEMP AND TGFEST.CODPROD = ITE.CODPROD AND ITE.CONTROLE = TGFEST.CONTROLE AND ITE.CODLOCALORIG=TGFEST.CODLOCAL GROUP BY DTVAL) as DTVAL,
     NVL(ITEPA.CODPROD,ITE.CODPROD) CODPRODPA,
     --((NVL(ITEPA.QTDNEG,ITE.QTDNEG)/ITE.QTDNEG) * PRO.PESOLIQ) PESO_UNIT
    SUM((ITE.QTDNEG*PRO.PESOLIQ)/ITEPA.QTDNEG) PESO_UNIT
FROM TGFCAB CAB
INNER JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA AND LIB.EVENTO IN (18) AND ((LIB.DHLIB IS NOT NULL AND LIB.VLRLIBERADO >= LIB.VLRATUAL) OR LIB.DHLIB IS NULL)
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
INNER JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA AND ITE.USOPROD IN ('R','D')
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
INNER JOIN TGFTOP TP ON TP.CODTIPOPER = CAB.CODTIPOPER AND TP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = TP.CODTIPOPER)
LEFT JOIN TGFITE ITEPA ON ITEPA.NUNOTA = CAB.NUNOTA AND ITEPA.USOPROD='V'
--INNER JOIN TGFITE ITEO ON ITEO.NUNOTA = VAR.NUNOTAORIG AND ITEO.SEQUENCIA = VAR.SEQUENCIAORIG AND ITEO.USOPROD = 'V'
LEFT JOIN TGFLOC LOC ON LOC.CODLOCAL = NVL(ITEPA.CODLOCALORIG,ITE.CODLOCALORIG)
LEFT JOIN TGFPRO PROV ON PROV.CODPROD = ITEPA.CODPROD
INNER JOIN TGFTPV TPV ON TPV.CODTIPVENDA = CAB.CODTIPVENDA AND CAB.DHTIPVENDA = TPV.DHALTER
WHERE CAB.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN AND
(:DF is null or  CAB.DTNEG <= :DF) AND
(:NROUNICO is null or   CAB.NUNOTA in (:NROUNICO))
AND (CAB.STATUSNFE<>'A'OR CAB.STATUSNFE IS NULL)
AND CAB.CODEMP = :CODEMP
AND NVL(TP.AD_ORDEMFAB,'N') = 'S'


GROUP BY
    CAB.NUMNOTA,
    CAB.NUNOTA,
	CAB.DTNEG,
    PRO.REFERENCIA,
    ITE.CODPROD,
	PRO.DESCRPROD,
	ITE.CONTROLE,
    ITE.USOPROD,
    PROV.CODPROD,
    PRO.CODPROD,
    PROV.DESCRPROD,
    PRO.DESCRPROD,
    PAR.CODPARC,
    PAR.RAZAOSOCIAL,
    PRO.PESOLIQ,
    ITE.CODLOCALORIG,
    LOC.DESCRLOCAL,
    VEN.APELIDO,
    ITE.CODVOL,
    ITEPA.VLRUNIT,
    ITEPA.CODPROD,
    ITE.VLRUNIT,
     CAB.AD_MARGEMMEDIA,
     CAB.AD_VALOR_FRETE,
     TPV.DESCRTIPVENDA,
     CAB.MODENTREGA,
     ITE.CONTROLE,CAB.CODEMP
,DTPREVENT

),


COMPRA as (
SELECT  ITE.CODPROD,
        ITE.CONTROLE,
        CAB.NUNOTA,
        CAB.NUMNOTA
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON ITE.NUNOTA=CAB.NUNOTA
WHERE CAB.TIPMOV = 'C'
     -- AND ITE.CODPROD = 1 AND ITE.CONTROLE = '1'
      and CAB.NUNOTA = (SELECT MAX(TGFCAB.NUNOTA)
                    FROM TGFCAB
                    INNER JOIN TGFITE ITESUB ON ITESUB.NUNOTA = TGFCAB.NUNOTA AND ITESUB.CODPROD = ITE.CODPROD) ),
PESO AS (SELECT SUM(PESO_UNIT) PESOCESTA,NUNOTA FROM A GROUP BY NUNOTA)



SELECT A.NUMNOTA,
    A.NUNOTA,
	A.DTNEG,
    A.REFERENCIA,
    A.CODPROD,
	A.DESCRPROD,
	A.CONTROLE,
    A.USOPROD,
    A.CODCESTA,
    A.CESTA,
    SUM(A.QTDNEG) OVER (PARTITION BY A.NUNOTA, A.CODPROD, A.CONTROLE) / A.QTDNEGPA AS UNIT,
    SUM(A.QTDNEG) OVER (PARTITION BY A.NUNOTA, A.CODPROD, A.CONTROLE) AS QTDNEG,
    A.QTDNEGPA,
    SUM(A.QTDNEGPA) OVER() AS QTDNEGPATOT,
    A.CODPARC,
    A.RAZAOSOCIAL,
    A.PESO,
    A.CODLOCALORIG,
    A.DESCRLOCAL,
    A.APELIDO,
    A.CODVOL,
    A.DTFAB,
    A.MODENTREGA,
    A.VLRUNIT,
    A.AD_MARGEMMEDIA,
    A.AD_VALOR_FRETE,
    A.DESCRTIPVENDA,
    A.DTVAL,
    A.CODPRODPA,
    SUM(A.PESO_UNIT) OVER (PARTITION BY A.NUNOTA, A.CODPROD, A.CONTROLE) AS PESO_UNIT,
    C.NUMNOTA,
    TO_CHAR(PESO.PESOCESTA) AS VAL
FROM A
    INNER JOIN PESO ON PESO.NUNOTA=A.NUNOTA
LEFT JOIN COMPRA C ON C.CODPROD = A.CODPROD AND A.CONTROLE = C.CONTROLE
order by A.NUNOTA, A.DESCRPROD