CREATE OR REPLACE TRIGGER "TESTE2"."TRG_INC_UPD_TGFCABOC" BEFORE UPDATE  ON TGFCAB
FOR EACH ROW
DECLARE
	ERRMSG			VARCHAR(255);
	P_ERRMSG          VARCHAR2(255);
	P_COUNT    INT;
	P_DHBAIXA DATE;
	P_TIPNEG  INT;
	P_VALIDAR	BOOLEAN;
	P_CODTIPOPER INT;
	ERROR  EXCEPTION;
BEGIN
  IF STP_GET_ATUALIZANDO THEN
    RETURN;
  END IF;
 	P_VALIDAR := Fpodevalidar ('TGFCAB');
	IF (NOT P_VALIDAR)
	THEN
		RETURN;
	END IF;

  IF UPDATING('ORDEMCARGA') OR NVL(:NEW.ORDEMCARGA,0) <> NVL(:OLD.ORDEMCARGA,0) THEN


  BEGIN
	SELECT
	COUNT(1),
	CODTIPTIT,
	CODTIPOPER,
	DHBAIXA
	 INTO
	P_COUNT,
	P_TIPNEG,
	P_CODTIPOPER,
	P_DHBAIXA
FROM
	TGFFIN
WHERE
	NUNOTA = :NEW.NUNOTA
	AND CODTIPTIT = 11
GROUP BY
	CODTIPTIT,
	CODTIPOPER,
	DHBAIXA;

EXCEPTION
WHEN NO_DATA_FOUND THEN
            P_DHBAIXA := NULL;
END;


     IF (P_COUNT = 1) AND P_DHBAIXA IS NULL AND P_CODTIPOPER = 1126  THEN
        ERRMSG := 'Título ainda não foi baixado, não pode alterar a Ordem de Carga';
		RAISE ERROR;
     END IF;
END IF;
	RETURN;
		EXCEPTION
			WHEN ERROR THEN
			RAISE_APPLICATION_ERROR(-20101, ERRMSG);


END;
